#!/usr/bin/env python

import sys
from subprocess import call

# Example cmds: build --app ride --store samsung --type release --plus
# will run ./gradlew -a MapmyrideplusSamsungRelease

if len(sys.argv) <= 2:
    print "Flavor type not supplied. Defaulting to MapmyhikeGoogleDebug"

name = "Hike"
store = "Google"
rType = "Debug"
isPlus = False

for i in range(1, len(sys.argv)):
    val = sys.argv[i]
    if "--" in val:
        if "app" in val:
            i = i + 1
            name = sys.argv[i]
        
        elif "store" in val:
            i = i + 1
            store = sys.argv[i].capitalize()

        elif "type" in val:
            i = i + 1
            rType = sys.argv[i]

        elif "plus" in val:
            isPlus = True

cmd = "assembleMapmy" + name + ("Plus" if isPlus else "") + store + rType
call(["./gradlew", "-a", cmd])

