#!/usr/bin/python

import os
import sys

from subprocess import call

ARGUMENTS = {}

for i in range(1, len(sys.argv)):
	arg = sys.argv[i]

	if "--" in arg:
		if "path" in arg:
			ARGUMENTS["path"] = sys.argv[i + 1]
			i = i + 1

		if "res" in arg:
			ARGUMENTS["res"] = sys.argv[i + 1]
			i = i + 1

PATH = None
RES = None

try:
	PATH = ARGUMENTS["path"]
except KeyError:
	print "missing --path.  this is the path to the android repo"
	sys.exit(2)

try:
	RES = ARGUMENTS["res"]
except KeyError:
	RES = os.path.join("application", "src", "main", "res")

PATH = os.path.join(PATH, RES)
if not os.path.isdir(PATH):
	print "invalid res dir"
	sys.exit(2)

cache = {}

for root, dirs, files in os.walk(os.getcwd()):
	for f in files:
		path = os.path.join(root, f)

		if "@3x" in f:
			cache[path] = os.path.join(PATH, "drawable-xxhdpi", f.replace("@3x", ""))

		if "@2x" in f:
			cache[path] = os.path.join(PATH, "drawable-xhdpi", f.replace("@2x", ""))
			
		if "@1.5x" in f:
			cache[path] = os.path.join(PATH, "drawable-hdpi", f.replace("@1.5x", ""))

		if "@1x" in f:
			cache[path] = os.path.join(PATH, "drawable-mdpi", f.replace("@1x", ""))


for key, value in cache.iteritems():
	call(["mv", key, value])
