#!/usr/bin/python

import os
import sys

from subprocess import call

ARGUMENTS = {}

for i in range(1, len(sys.argv)):
	arg = sys.argv[i]

	if "--" in arg:
		if "path" in arg:
			ARGUMENTS["path"] = sys.argv[i + 1]
			i = i + 1

PATH = None

try:
	PATH = ARGUMENTS["path"]
except KeyError:
	print "missing --path.  this is the path to the res dir.  i.e. androidProj/src/main/res/"
	sys.exit(2)

if not os.path.isdir(PATH):
	print "invalid res dir"
	sys.exit(2)

cache = {}

for root, dirs, files in os.walk(os.getcwd()):
	for f in files:
		path = os.path.join(root, f)

		if "@3x" in f:
			cache[path] = os.path.join(PATH, "drawable-xxhdpi", f.replace("@3x", ""))

		elif "@2x" in f:
			cache[path] = os.path.join(PATH, "drawable-xhdpi", f.replace("@2x", ""))
			
		elif "@1.5x" in f:
			cache[path] = os.path.join(PATH, "drawable-hdpi", f.replace("@1.5x", ""))

		else:
			cache[path] = os.path.join(PATH, "drawable-mdpi", f.replace("@1x", ""))


for key, value in cache.iteritems():
	call(["mv", key, value])
